version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: abbes
      POSTGRES_PASSWORD: abbes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: abbes@abbes.com
      PGADMIN_DEFAULT_PASSWORD: abbes
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
